{
 "title": "Matchmaker",
 "time": { "from": "now-10m", "to": "now" },
 "panels": [
  {
   "title": "Prometheus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_http_request_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Http Request Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_request_total" }
   ]
  },
  {
   "title": "System cpu usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_usage" },
    {}
   ]
  }
 ]
}